# Git aliases
alias gshow='git show --pretty=fuller'
alias ga='git add'
alias gp='git push'
alias gst='git stash'
alias gstp='git stash pop'
alias gfp='git ftp push'
alias gl='git graph-log'
alias gla='git graph-log --all'
alias gs='git status -sb'
alias gd="git diff --word-diff"
alias gm='git commit -m'
alias gma='git commit -am'
alias gca='git commit --amend'
alias gmg='git merge --no-ff'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull --rebase'
alias gcl='git clone'
alias grm='git rebase master'
